version: "3"

services:
  chirp:
    env_file: .env
    hostname: chirp
    build:
      context: .
      dockerfile: Dockerfile.debian
      labels:
        # workaround around a docker-compose bug when image is also used by docker run (https://github.com/docker/compose/issues/10162)
        com.docker.compose.container-number: "1"
      args:
        VERSION: $VERSION
        INSTALL_USER: $INSTALL_USER
    image: chirp
    container_name: chirp
    volumes:
      - $HOME/.Xauthority:/home/chirp/.Xauthority
      - $PWD:/home/chirp
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: "host"
    command: >
      /usr/local/bin/chirp
