version: "3"

services:
  chirp:
    hostname: chirp
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        VERSION: "20221217"
        INSTALL_USER: "chirp"
    image: chirp
    container_name: chirp
    volumes:
      - $HOME/.Xauthority:/home/chirp/.Xauthority
      - $PWD:/home/chirp
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: "host"
    command: >
      /usr/local/bin/chirp/chirpw
